# Generated by Django 4.2.4 on 2023-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("filter_set", models.JSONField()),
                ("graph_filter_set", models.JSONField()),
            ],
        ),
    ]
