# Generated by Django 4.2.4 on 2024-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0002_filtersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filtersettings",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
