# Generated by Django 4.2.4 on 2024-04-18 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0003_alter_filtersettings_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeseriesData",
        ),
    ]
