# Generated by Django 4.2.4 on 2024-04-18 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0005_result_remove_scalardata_scenario_delete_scenario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scalardata",
            old_name="input_energy_vector",
            new_name="input_commodity",
        ),
        migrations.RenameField(
            model_name="scalardata",
            old_name="output_energy_vector",
            new_name="output_commodity",
        ),
        migrations.RenameField(
            model_name="scalardata",
            old_name="parameter_name",
            new_name="parameter",
        ),
        migrations.RenameField(
            model_name="scalardata",
            old_name="technology",
            new_name="process",
        ),
        migrations.RenameField(
            model_name="scalardata",
            old_name="region",
            new_name="scenario",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="method",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="source",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="technology_type",
        ),
        migrations.AddField(
            model_name="scalardata",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scalardata",
            name="groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="scalardata",
            name="new",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scalardata",
            name="sector",
            field=models.CharField(default="ind", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scalardata",
            name="specification",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
