# Generated by Django 4.2.4 on 2024-06-06 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0006_rename_input_energy_vector_scalardata_input_commodity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scalardata",
            name="input_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="scalardata",
            name="output_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
    ]
