# Generated by Django 4.2.4 on 2024-06-25 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0007_scalardata_input_groups_scalardata_output_groups"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FilterSettings",
            new_name="NamedFilterSettings",
        ),
    ]
