# Generated by Django 4.2.4 on 2024-06-25 13:22

from django.db import migrations, models
import django.db.models.deletion


def migrate_filter_settings(apps, schema_editor):
    FilterSettings = apps.get_model('django_comparison_dashboard', 'FilterSettings')
    NamedFilterSettings = apps.get_model('django_comparison_dashboard', 'NamedFilterSettings')
    for named_filter in NamedFilterSettings.objects.all():
        fs = FilterSettings(filter_set=named_filter.filter_set, graph_filter_set=named_filter.graph_filter_set)
        fs.save()
        named_filter.filter_settings = fs
        named_filter.save()


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0009_filtersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedfiltersettings",
            name="filter_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="django_comparison_dashboard.filtersettings",
            ),
        ),
        migrations.RunPython(
            migrate_filter_settings,
            reverse_code=None
        ),
    ]
