# Generated by Django 4.2.4 on 2024-06-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0011_remove_namedfiltersettings_filter_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedfiltersettings",
            name="filter_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="django_comparison_dashboard.filtersettings"
            ),
        ),
    ]
