# Generated by Django 4.2.4 on 2024-06-28 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_comparison_dashboard", "0012_alter_namedfiltersettings_filter_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scalardata",
            name="input_commodity",
        ),
        migrations.RemoveField(
            model_name="scalardata",
            name="output_commodity",
        ),
    ]
